stages:
  - build
  - check
  - cleanup

.global-rules:
  image: node:20
  dependencies:
    - install_modules

install_modules:
  stage: build
  image: node:20
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - package-lock.json

lint:
  stage: check
  extends: .global-rules
  script:
    - npm run lint
  allow_failure: false

format:
  stage: check
  extends: .global-rules
  script:
    - npm run prettier
  allow_failure: false

delete_artifacts:
  image: alpine:latest
  stage: cleanup
  before_script:
    - apk add --update curl
  script:
    - 'curl --request DELETE --header "PRIVATE-TOKEN: $ACCESS_TOKEN" "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/artifacts"'
  when: always
