stages:
  - build
  - check
  - cleanup

.global-rules:
  image: node:20
  dependencies:
    - install_modules

install_modules:
  except:
      - main
  stage: build
  image: node:20
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - package-lock.json

lint:
  except:
      - main
  stage: check
  extends: .global-rules
  script:
    - npm run lint
  allow_failure: false

standards:
  except:
      - main
  stage: check
  extends: .global-rules
  script:
    - npm run standard
  allow_failure: false

format:
  except:
      - main
  stage: check
  extends: .global-rules
  script:
    - npm run prettier
  allow_failure: false

delete_artifacts:
  except:
        - main
  image: alpine:latest
  stage: cleanup
  before_script:
    - apk add --update curl
  script:
    - 'curl --request DELETE --header "PRIVATE-TOKEN: $ACCESS_TOKEN" "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/jobs/$CI_JOB_ID/artifacts"'
  when: always

delete_pipelines:
  image: alpine:latest
  stage: cleanup
  before_script:
    - apk add --update curl
  script:
    - 'for i in {1..30}; do curl --request DELETE --header "PRIVATE-TOKEN: $ACCESS_TOKEN" "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/pipelines/$i"; done'
  when: always